#!/usr/bin/python3
from typing import List, Tuple, Optional
import subprocess, tempfile
from objects import *

def read_rules(fname):
    f = open(fname)
    rules = f.read().splitlines()
    f.close()
    pos_tags = set()
    for rule in rules:
        l, r = rule.split(' -> ')
        rl = r.split()
        pos_tags.add(l)
        pos_tags.update(rl)
        Rule(l, rl)
    for tag in pos_tags:
        Pattern(tag)

def generate_file(fname):
    f = open(fname, 'w')
    for name, attr in sorted(Attribute.all_attrs.items()):
        f.write(str(attr) + '\n')
    f.write('\n\n')
    for name, pat in sorted(Pattern.all_patterns.items()):
        f.write(str(pat) + '\n')
    f.write('\n\n')
    for name, rule in sorted(Rule.all_rules.items()):
        f.write(str(rule) + '\n\n')
    f.close()

def align_corpus(sens):
    for i, (a, b) in enumerate(sens):
        print('---------------------')
        al = a.align(b.children)
        a.filter_align(al)
        a.suggest_rules([i], b.children)
        print(al)
        print(a)
        print(b)

if __name__ == '__main__':
    import corpus
    parser = corpus.make_corpus_argparse('generate rtx rules from skelton CFG file')
    parser.add_argument('cfg_rules', help='new-line separated CFG rules, such as generated by rtx-comp -s')
    parser.add_argument('rtx_file', help='file to write generated rules to')
    args = parser.parse_args()
    read_rules(args.cfg_rules)
    generate_file(args.rtx_file)
    binfile = open('whatever.bin', 'wb')#tempfile.NamedTemporaryFile()
    subprocess.run(['rtx-comp', args.rtx_file, binfile.name])
    sens = corpus.get_corpus(args, binfile.name)
    align_corpus(sens)
